/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedTsWorkRouteImport } from './routes/_authenticated/ts.work'
import { Route as AuthenticatedTsMyWarningsRouteImport } from './routes/_authenticated/ts.my-warnings'
import { Route as AuthenticatedTsMyReportRouteImport } from './routes/_authenticated/ts.my-report'
import { Route as AuthenticatedTsCallLaterRouteImport } from './routes/_authenticated/ts.call-later'
import { Route as AuthenticatedTsCallHistoryRouteImport } from './routes/_authenticated/ts.call-history'
import { Route as AuthenticatedSettingsChangePasswordRouteImport } from './routes/_authenticated/settings.change-password'
import { Route as AuthenticatedQaWorkRouteImport } from './routes/_authenticated/qa.work'
import { Route as AuthenticatedQaCallLaterRouteImport } from './routes/_authenticated/qa.call-later'
import { Route as AuthenticatedQaCallHistoryRouteImport } from './routes/_authenticated/qa.call-history'
import { Route as AuthenticatedTsReportsLeadsRouteImport } from './routes/_authenticated/ts.reports.leads'
import { Route as AuthenticatedTsReportsCallsRouteImport } from './routes/_authenticated/ts.reports.calls'
import { Route as AuthenticatedTsReportsAgentsRouteImport } from './routes/_authenticated/ts.reports.agents'
import { Route as AuthenticatedTsAdminWarningsRouteImport } from './routes/_authenticated/ts.admin.warnings'
import { Route as AuthenticatedTsAdminValidationRouteImport } from './routes/_authenticated/ts.admin.validation'
import { Route as AuthenticatedTsAdminUsersRouteImport } from './routes/_authenticated/ts.admin.users'
import { Route as AuthenticatedTsAdminTargetsRouteImport } from './routes/_authenticated/ts.admin.targets'
import { Route as AuthenticatedTsAdminFormsRouteImport } from './routes/_authenticated/ts.admin.forms'
import { Route as AuthenticatedTsAdminCampaignsRouteImport } from './routes/_authenticated/ts.admin.campaigns'
import { Route as AuthenticatedTsAdminCallResultsRouteImport } from './routes/_authenticated/ts.admin.call-results'
import { Route as AuthenticatedTsAdminBatchesRouteImport } from './routes/_authenticated/ts.admin.batches'
import { Route as AuthenticatedTsAdminAuditLogRouteImport } from './routes/_authenticated/ts.admin.audit-log'
import { Route as AuthenticatedTsAdminActivationRouteImport } from './routes/_authenticated/ts.admin.activation'
import { Route as AuthenticatedQaReportsTeamsRouteImport } from './routes/_authenticated/qa.reports.teams'
import { Route as AuthenticatedQaReportsSalesRepsRouteImport } from './routes/_authenticated/qa.reports.sales-reps'
import { Route as AuthenticatedQaReportsEvaluationsRouteImport } from './routes/_authenticated/qa.reports.evaluations'
import { Route as AuthenticatedQaReportsCustomersRouteImport } from './routes/_authenticated/qa.reports.customers'
import { Route as AuthenticatedQaReportsCallsRouteImport } from './routes/_authenticated/qa.reports.calls'
import { Route as AuthenticatedQaReportsBatchesRouteImport } from './routes/_authenticated/qa.reports.batches'
import { Route as AuthenticatedQaReportsAgentsRouteImport } from './routes/_authenticated/qa.reports.agents'
import { Route as AuthenticatedQaAdminUsersRouteImport } from './routes/_authenticated/qa.admin.users'
import { Route as AuthenticatedQaAdminSalesRepsRouteImport } from './routes/_authenticated/qa.admin.sales-reps'
import { Route as AuthenticatedQaAdminImportRouteImport } from './routes/_authenticated/qa.admin.import'
import { Route as AuthenticatedManagerTsLeadsRouteImport } from './routes/_authenticated/manager.ts.leads'
import { Route as AuthenticatedManagerTsCampaignsRouteImport } from './routes/_authenticated/manager.ts.campaigns'
import { Route as AuthenticatedManagerTsCallsRouteImport } from './routes/_authenticated/manager.ts.calls'
import { Route as AuthenticatedManagerTsBatchesRouteImport } from './routes/_authenticated/manager.ts.batches'
import { Route as AuthenticatedManagerTsAgentsRouteImport } from './routes/_authenticated/manager.ts.agents'
import { Route as AuthenticatedManagerQaTeamsRouteImport } from './routes/_authenticated/manager.qa.teams'
import { Route as AuthenticatedManagerQaSalesRepsRouteImport } from './routes/_authenticated/manager.qa.sales-reps'
import { Route as AuthenticatedManagerQaEvaluationsRouteImport } from './routes/_authenticated/manager.qa.evaluations'
import { Route as AuthenticatedManagerQaCustomersRouteImport } from './routes/_authenticated/manager.qa.customers'
import { Route as AuthenticatedManagerQaCallsRouteImport } from './routes/_authenticated/manager.qa.calls'
import { Route as AuthenticatedManagerQaBatchesRouteImport } from './routes/_authenticated/manager.qa.batches'
import { Route as AuthenticatedManagerQaAgentsRouteImport } from './routes/_authenticated/manager.qa.agents'
import { Route as AuthenticatedQaReportsSalesRepsIdRouteImport } from './routes/_authenticated/qa.reports.sales-reps.$id'
import { Route as AuthenticatedQaReportsEvaluationsIdRouteImport } from './routes/_authenticated/qa.reports.evaluations.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/manager/',
    path: '/manager/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsWorkRoute = AuthenticatedTsWorkRouteImport.update({
  id: '/ts/work',
  path: '/ts/work',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTsMyWarningsRoute =
  AuthenticatedTsMyWarningsRouteImport.update({
    id: '/ts/my-warnings',
    path: '/ts/my-warnings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsMyReportRoute = AuthenticatedTsMyReportRouteImport.update({
  id: '/ts/my-report',
  path: '/ts/my-report',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTsCallLaterRoute =
  AuthenticatedTsCallLaterRouteImport.update({
    id: '/ts/call-later',
    path: '/ts/call-later',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsCallHistoryRoute =
  AuthenticatedTsCallHistoryRouteImport.update({
    id: '/ts/call-history',
    path: '/ts/call-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsChangePasswordRoute =
  AuthenticatedSettingsChangePasswordRouteImport.update({
    id: '/settings/change-password',
    path: '/settings/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaWorkRoute = AuthenticatedQaWorkRouteImport.update({
  id: '/qa/work',
  path: '/qa/work',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQaCallLaterRoute =
  AuthenticatedQaCallLaterRouteImport.update({
    id: '/qa/call-later',
    path: '/qa/call-later',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaCallHistoryRoute =
  AuthenticatedQaCallHistoryRouteImport.update({
    id: '/qa/call-history',
    path: '/qa/call-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsReportsLeadsRoute =
  AuthenticatedTsReportsLeadsRouteImport.update({
    id: '/ts/reports/leads',
    path: '/ts/reports/leads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsReportsCallsRoute =
  AuthenticatedTsReportsCallsRouteImport.update({
    id: '/ts/reports/calls',
    path: '/ts/reports/calls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsReportsAgentsRoute =
  AuthenticatedTsReportsAgentsRouteImport.update({
    id: '/ts/reports/agents',
    path: '/ts/reports/agents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsAdminWarningsRoute =
  AuthenticatedTsAdminWarningsRouteImport.update({
    id: '/ts/admin/warnings',
    path: '/ts/admin/warnings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsAdminValidationRoute =
  AuthenticatedTsAdminValidationRouteImport.update({
    id: '/ts/admin/validation',
    path: '/ts/admin/validation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsAdminUsersRoute =
  AuthenticatedTsAdminUsersRouteImport.update({
    id: '/ts/admin/users',
    path: '/ts/admin/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsAdminTargetsRoute =
  AuthenticatedTsAdminTargetsRouteImport.update({
    id: '/ts/admin/targets',
    path: '/ts/admin/targets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsAdminFormsRoute =
  AuthenticatedTsAdminFormsRouteImport.update({
    id: '/ts/admin/forms',
    path: '/ts/admin/forms',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsAdminCampaignsRoute =
  AuthenticatedTsAdminCampaignsRouteImport.update({
    id: '/ts/admin/campaigns',
    path: '/ts/admin/campaigns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsAdminCallResultsRoute =
  AuthenticatedTsAdminCallResultsRouteImport.update({
    id: '/ts/admin/call-results',
    path: '/ts/admin/call-results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsAdminBatchesRoute =
  AuthenticatedTsAdminBatchesRouteImport.update({
    id: '/ts/admin/batches',
    path: '/ts/admin/batches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsAdminAuditLogRoute =
  AuthenticatedTsAdminAuditLogRouteImport.update({
    id: '/ts/admin/audit-log',
    path: '/ts/admin/audit-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTsAdminActivationRoute =
  AuthenticatedTsAdminActivationRouteImport.update({
    id: '/ts/admin/activation',
    path: '/ts/admin/activation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaReportsTeamsRoute =
  AuthenticatedQaReportsTeamsRouteImport.update({
    id: '/qa/reports/teams',
    path: '/qa/reports/teams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaReportsSalesRepsRoute =
  AuthenticatedQaReportsSalesRepsRouteImport.update({
    id: '/qa/reports/sales-reps',
    path: '/qa/reports/sales-reps',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaReportsEvaluationsRoute =
  AuthenticatedQaReportsEvaluationsRouteImport.update({
    id: '/qa/reports/evaluations',
    path: '/qa/reports/evaluations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaReportsCustomersRoute =
  AuthenticatedQaReportsCustomersRouteImport.update({
    id: '/qa/reports/customers',
    path: '/qa/reports/customers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaReportsCallsRoute =
  AuthenticatedQaReportsCallsRouteImport.update({
    id: '/qa/reports/calls',
    path: '/qa/reports/calls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaReportsBatchesRoute =
  AuthenticatedQaReportsBatchesRouteImport.update({
    id: '/qa/reports/batches',
    path: '/qa/reports/batches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaReportsAgentsRoute =
  AuthenticatedQaReportsAgentsRouteImport.update({
    id: '/qa/reports/agents',
    path: '/qa/reports/agents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaAdminUsersRoute =
  AuthenticatedQaAdminUsersRouteImport.update({
    id: '/qa/admin/users',
    path: '/qa/admin/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaAdminSalesRepsRoute =
  AuthenticatedQaAdminSalesRepsRouteImport.update({
    id: '/qa/admin/sales-reps',
    path: '/qa/admin/sales-reps',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaAdminImportRoute =
  AuthenticatedQaAdminImportRouteImport.update({
    id: '/qa/admin/import',
    path: '/qa/admin/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerTsLeadsRoute =
  AuthenticatedManagerTsLeadsRouteImport.update({
    id: '/manager/ts/leads',
    path: '/manager/ts/leads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerTsCampaignsRoute =
  AuthenticatedManagerTsCampaignsRouteImport.update({
    id: '/manager/ts/campaigns',
    path: '/manager/ts/campaigns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerTsCallsRoute =
  AuthenticatedManagerTsCallsRouteImport.update({
    id: '/manager/ts/calls',
    path: '/manager/ts/calls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerTsBatchesRoute =
  AuthenticatedManagerTsBatchesRouteImport.update({
    id: '/manager/ts/batches',
    path: '/manager/ts/batches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerTsAgentsRoute =
  AuthenticatedManagerTsAgentsRouteImport.update({
    id: '/manager/ts/agents',
    path: '/manager/ts/agents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerQaTeamsRoute =
  AuthenticatedManagerQaTeamsRouteImport.update({
    id: '/manager/qa/teams',
    path: '/manager/qa/teams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerQaSalesRepsRoute =
  AuthenticatedManagerQaSalesRepsRouteImport.update({
    id: '/manager/qa/sales-reps',
    path: '/manager/qa/sales-reps',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerQaEvaluationsRoute =
  AuthenticatedManagerQaEvaluationsRouteImport.update({
    id: '/manager/qa/evaluations',
    path: '/manager/qa/evaluations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerQaCustomersRoute =
  AuthenticatedManagerQaCustomersRouteImport.update({
    id: '/manager/qa/customers',
    path: '/manager/qa/customers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerQaCallsRoute =
  AuthenticatedManagerQaCallsRouteImport.update({
    id: '/manager/qa/calls',
    path: '/manager/qa/calls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerQaBatchesRoute =
  AuthenticatedManagerQaBatchesRouteImport.update({
    id: '/manager/qa/batches',
    path: '/manager/qa/batches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerQaAgentsRoute =
  AuthenticatedManagerQaAgentsRouteImport.update({
    id: '/manager/qa/agents',
    path: '/manager/qa/agents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaReportsSalesRepsIdRoute =
  AuthenticatedQaReportsSalesRepsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedQaReportsSalesRepsRoute,
  } as any)
const AuthenticatedQaReportsEvaluationsIdRoute =
  AuthenticatedQaReportsEvaluationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedQaReportsEvaluationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/qa/call-history': typeof AuthenticatedQaCallHistoryRoute
  '/qa/call-later': typeof AuthenticatedQaCallLaterRoute
  '/qa/work': typeof AuthenticatedQaWorkRoute
  '/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/ts/call-history': typeof AuthenticatedTsCallHistoryRoute
  '/ts/call-later': typeof AuthenticatedTsCallLaterRoute
  '/ts/my-report': typeof AuthenticatedTsMyReportRoute
  '/ts/my-warnings': typeof AuthenticatedTsMyWarningsRoute
  '/ts/work': typeof AuthenticatedTsWorkRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
  '/manager/qa/agents': typeof AuthenticatedManagerQaAgentsRoute
  '/manager/qa/batches': typeof AuthenticatedManagerQaBatchesRoute
  '/manager/qa/calls': typeof AuthenticatedManagerQaCallsRoute
  '/manager/qa/customers': typeof AuthenticatedManagerQaCustomersRoute
  '/manager/qa/evaluations': typeof AuthenticatedManagerQaEvaluationsRoute
  '/manager/qa/sales-reps': typeof AuthenticatedManagerQaSalesRepsRoute
  '/manager/qa/teams': typeof AuthenticatedManagerQaTeamsRoute
  '/manager/ts/agents': typeof AuthenticatedManagerTsAgentsRoute
  '/manager/ts/batches': typeof AuthenticatedManagerTsBatchesRoute
  '/manager/ts/calls': typeof AuthenticatedManagerTsCallsRoute
  '/manager/ts/campaigns': typeof AuthenticatedManagerTsCampaignsRoute
  '/manager/ts/leads': typeof AuthenticatedManagerTsLeadsRoute
  '/qa/admin/import': typeof AuthenticatedQaAdminImportRoute
  '/qa/admin/sales-reps': typeof AuthenticatedQaAdminSalesRepsRoute
  '/qa/admin/users': typeof AuthenticatedQaAdminUsersRoute
  '/qa/reports/agents': typeof AuthenticatedQaReportsAgentsRoute
  '/qa/reports/batches': typeof AuthenticatedQaReportsBatchesRoute
  '/qa/reports/calls': typeof AuthenticatedQaReportsCallsRoute
  '/qa/reports/customers': typeof AuthenticatedQaReportsCustomersRoute
  '/qa/reports/evaluations': typeof AuthenticatedQaReportsEvaluationsRouteWithChildren
  '/qa/reports/sales-reps': typeof AuthenticatedQaReportsSalesRepsRouteWithChildren
  '/qa/reports/teams': typeof AuthenticatedQaReportsTeamsRoute
  '/ts/admin/activation': typeof AuthenticatedTsAdminActivationRoute
  '/ts/admin/audit-log': typeof AuthenticatedTsAdminAuditLogRoute
  '/ts/admin/batches': typeof AuthenticatedTsAdminBatchesRoute
  '/ts/admin/call-results': typeof AuthenticatedTsAdminCallResultsRoute
  '/ts/admin/campaigns': typeof AuthenticatedTsAdminCampaignsRoute
  '/ts/admin/forms': typeof AuthenticatedTsAdminFormsRoute
  '/ts/admin/targets': typeof AuthenticatedTsAdminTargetsRoute
  '/ts/admin/users': typeof AuthenticatedTsAdminUsersRoute
  '/ts/admin/validation': typeof AuthenticatedTsAdminValidationRoute
  '/ts/admin/warnings': typeof AuthenticatedTsAdminWarningsRoute
  '/ts/reports/agents': typeof AuthenticatedTsReportsAgentsRoute
  '/ts/reports/calls': typeof AuthenticatedTsReportsCallsRoute
  '/ts/reports/leads': typeof AuthenticatedTsReportsLeadsRoute
  '/qa/reports/evaluations/$id': typeof AuthenticatedQaReportsEvaluationsIdRoute
  '/qa/reports/sales-reps/$id': typeof AuthenticatedQaReportsSalesRepsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/qa/call-history': typeof AuthenticatedQaCallHistoryRoute
  '/qa/call-later': typeof AuthenticatedQaCallLaterRoute
  '/qa/work': typeof AuthenticatedQaWorkRoute
  '/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/ts/call-history': typeof AuthenticatedTsCallHistoryRoute
  '/ts/call-later': typeof AuthenticatedTsCallLaterRoute
  '/ts/my-report': typeof AuthenticatedTsMyReportRoute
  '/ts/my-warnings': typeof AuthenticatedTsMyWarningsRoute
  '/ts/work': typeof AuthenticatedTsWorkRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/manager/qa/agents': typeof AuthenticatedManagerQaAgentsRoute
  '/manager/qa/batches': typeof AuthenticatedManagerQaBatchesRoute
  '/manager/qa/calls': typeof AuthenticatedManagerQaCallsRoute
  '/manager/qa/customers': typeof AuthenticatedManagerQaCustomersRoute
  '/manager/qa/evaluations': typeof AuthenticatedManagerQaEvaluationsRoute
  '/manager/qa/sales-reps': typeof AuthenticatedManagerQaSalesRepsRoute
  '/manager/qa/teams': typeof AuthenticatedManagerQaTeamsRoute
  '/manager/ts/agents': typeof AuthenticatedManagerTsAgentsRoute
  '/manager/ts/batches': typeof AuthenticatedManagerTsBatchesRoute
  '/manager/ts/calls': typeof AuthenticatedManagerTsCallsRoute
  '/manager/ts/campaigns': typeof AuthenticatedManagerTsCampaignsRoute
  '/manager/ts/leads': typeof AuthenticatedManagerTsLeadsRoute
  '/qa/admin/import': typeof AuthenticatedQaAdminImportRoute
  '/qa/admin/sales-reps': typeof AuthenticatedQaAdminSalesRepsRoute
  '/qa/admin/users': typeof AuthenticatedQaAdminUsersRoute
  '/qa/reports/agents': typeof AuthenticatedQaReportsAgentsRoute
  '/qa/reports/batches': typeof AuthenticatedQaReportsBatchesRoute
  '/qa/reports/calls': typeof AuthenticatedQaReportsCallsRoute
  '/qa/reports/customers': typeof AuthenticatedQaReportsCustomersRoute
  '/qa/reports/evaluations': typeof AuthenticatedQaReportsEvaluationsRouteWithChildren
  '/qa/reports/sales-reps': typeof AuthenticatedQaReportsSalesRepsRouteWithChildren
  '/qa/reports/teams': typeof AuthenticatedQaReportsTeamsRoute
  '/ts/admin/activation': typeof AuthenticatedTsAdminActivationRoute
  '/ts/admin/audit-log': typeof AuthenticatedTsAdminAuditLogRoute
  '/ts/admin/batches': typeof AuthenticatedTsAdminBatchesRoute
  '/ts/admin/call-results': typeof AuthenticatedTsAdminCallResultsRoute
  '/ts/admin/campaigns': typeof AuthenticatedTsAdminCampaignsRoute
  '/ts/admin/forms': typeof AuthenticatedTsAdminFormsRoute
  '/ts/admin/targets': typeof AuthenticatedTsAdminTargetsRoute
  '/ts/admin/users': typeof AuthenticatedTsAdminUsersRoute
  '/ts/admin/validation': typeof AuthenticatedTsAdminValidationRoute
  '/ts/admin/warnings': typeof AuthenticatedTsAdminWarningsRoute
  '/ts/reports/agents': typeof AuthenticatedTsReportsAgentsRoute
  '/ts/reports/calls': typeof AuthenticatedTsReportsCallsRoute
  '/ts/reports/leads': typeof AuthenticatedTsReportsLeadsRoute
  '/qa/reports/evaluations/$id': typeof AuthenticatedQaReportsEvaluationsIdRoute
  '/qa/reports/sales-reps/$id': typeof AuthenticatedQaReportsSalesRepsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/qa/call-history': typeof AuthenticatedQaCallHistoryRoute
  '/_authenticated/qa/call-later': typeof AuthenticatedQaCallLaterRoute
  '/_authenticated/qa/work': typeof AuthenticatedQaWorkRoute
  '/_authenticated/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/_authenticated/ts/call-history': typeof AuthenticatedTsCallHistoryRoute
  '/_authenticated/ts/call-later': typeof AuthenticatedTsCallLaterRoute
  '/_authenticated/ts/my-report': typeof AuthenticatedTsMyReportRoute
  '/_authenticated/ts/my-warnings': typeof AuthenticatedTsMyWarningsRoute
  '/_authenticated/ts/work': typeof AuthenticatedTsWorkRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/manager/qa/agents': typeof AuthenticatedManagerQaAgentsRoute
  '/_authenticated/manager/qa/batches': typeof AuthenticatedManagerQaBatchesRoute
  '/_authenticated/manager/qa/calls': typeof AuthenticatedManagerQaCallsRoute
  '/_authenticated/manager/qa/customers': typeof AuthenticatedManagerQaCustomersRoute
  '/_authenticated/manager/qa/evaluations': typeof AuthenticatedManagerQaEvaluationsRoute
  '/_authenticated/manager/qa/sales-reps': typeof AuthenticatedManagerQaSalesRepsRoute
  '/_authenticated/manager/qa/teams': typeof AuthenticatedManagerQaTeamsRoute
  '/_authenticated/manager/ts/agents': typeof AuthenticatedManagerTsAgentsRoute
  '/_authenticated/manager/ts/batches': typeof AuthenticatedManagerTsBatchesRoute
  '/_authenticated/manager/ts/calls': typeof AuthenticatedManagerTsCallsRoute
  '/_authenticated/manager/ts/campaigns': typeof AuthenticatedManagerTsCampaignsRoute
  '/_authenticated/manager/ts/leads': typeof AuthenticatedManagerTsLeadsRoute
  '/_authenticated/qa/admin/import': typeof AuthenticatedQaAdminImportRoute
  '/_authenticated/qa/admin/sales-reps': typeof AuthenticatedQaAdminSalesRepsRoute
  '/_authenticated/qa/admin/users': typeof AuthenticatedQaAdminUsersRoute
  '/_authenticated/qa/reports/agents': typeof AuthenticatedQaReportsAgentsRoute
  '/_authenticated/qa/reports/batches': typeof AuthenticatedQaReportsBatchesRoute
  '/_authenticated/qa/reports/calls': typeof AuthenticatedQaReportsCallsRoute
  '/_authenticated/qa/reports/customers': typeof AuthenticatedQaReportsCustomersRoute
  '/_authenticated/qa/reports/evaluations': typeof AuthenticatedQaReportsEvaluationsRouteWithChildren
  '/_authenticated/qa/reports/sales-reps': typeof AuthenticatedQaReportsSalesRepsRouteWithChildren
  '/_authenticated/qa/reports/teams': typeof AuthenticatedQaReportsTeamsRoute
  '/_authenticated/ts/admin/activation': typeof AuthenticatedTsAdminActivationRoute
  '/_authenticated/ts/admin/audit-log': typeof AuthenticatedTsAdminAuditLogRoute
  '/_authenticated/ts/admin/batches': typeof AuthenticatedTsAdminBatchesRoute
  '/_authenticated/ts/admin/call-results': typeof AuthenticatedTsAdminCallResultsRoute
  '/_authenticated/ts/admin/campaigns': typeof AuthenticatedTsAdminCampaignsRoute
  '/_authenticated/ts/admin/forms': typeof AuthenticatedTsAdminFormsRoute
  '/_authenticated/ts/admin/targets': typeof AuthenticatedTsAdminTargetsRoute
  '/_authenticated/ts/admin/users': typeof AuthenticatedTsAdminUsersRoute
  '/_authenticated/ts/admin/validation': typeof AuthenticatedTsAdminValidationRoute
  '/_authenticated/ts/admin/warnings': typeof AuthenticatedTsAdminWarningsRoute
  '/_authenticated/ts/reports/agents': typeof AuthenticatedTsReportsAgentsRoute
  '/_authenticated/ts/reports/calls': typeof AuthenticatedTsReportsCallsRoute
  '/_authenticated/ts/reports/leads': typeof AuthenticatedTsReportsLeadsRoute
  '/_authenticated/qa/reports/evaluations/$id': typeof AuthenticatedQaReportsEvaluationsIdRoute
  '/_authenticated/qa/reports/sales-reps/$id': typeof AuthenticatedQaReportsSalesRepsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/qa/call-history'
    | '/qa/call-later'
    | '/qa/work'
    | '/settings/change-password'
    | '/ts/call-history'
    | '/ts/call-later'
    | '/ts/my-report'
    | '/ts/my-warnings'
    | '/ts/work'
    | '/manager/'
    | '/manager/qa/agents'
    | '/manager/qa/batches'
    | '/manager/qa/calls'
    | '/manager/qa/customers'
    | '/manager/qa/evaluations'
    | '/manager/qa/sales-reps'
    | '/manager/qa/teams'
    | '/manager/ts/agents'
    | '/manager/ts/batches'
    | '/manager/ts/calls'
    | '/manager/ts/campaigns'
    | '/manager/ts/leads'
    | '/qa/admin/import'
    | '/qa/admin/sales-reps'
    | '/qa/admin/users'
    | '/qa/reports/agents'
    | '/qa/reports/batches'
    | '/qa/reports/calls'
    | '/qa/reports/customers'
    | '/qa/reports/evaluations'
    | '/qa/reports/sales-reps'
    | '/qa/reports/teams'
    | '/ts/admin/activation'
    | '/ts/admin/audit-log'
    | '/ts/admin/batches'
    | '/ts/admin/call-results'
    | '/ts/admin/campaigns'
    | '/ts/admin/forms'
    | '/ts/admin/targets'
    | '/ts/admin/users'
    | '/ts/admin/validation'
    | '/ts/admin/warnings'
    | '/ts/reports/agents'
    | '/ts/reports/calls'
    | '/ts/reports/leads'
    | '/qa/reports/evaluations/$id'
    | '/qa/reports/sales-reps/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/qa/call-history'
    | '/qa/call-later'
    | '/qa/work'
    | '/settings/change-password'
    | '/ts/call-history'
    | '/ts/call-later'
    | '/ts/my-report'
    | '/ts/my-warnings'
    | '/ts/work'
    | '/manager'
    | '/manager/qa/agents'
    | '/manager/qa/batches'
    | '/manager/qa/calls'
    | '/manager/qa/customers'
    | '/manager/qa/evaluations'
    | '/manager/qa/sales-reps'
    | '/manager/qa/teams'
    | '/manager/ts/agents'
    | '/manager/ts/batches'
    | '/manager/ts/calls'
    | '/manager/ts/campaigns'
    | '/manager/ts/leads'
    | '/qa/admin/import'
    | '/qa/admin/sales-reps'
    | '/qa/admin/users'
    | '/qa/reports/agents'
    | '/qa/reports/batches'
    | '/qa/reports/calls'
    | '/qa/reports/customers'
    | '/qa/reports/evaluations'
    | '/qa/reports/sales-reps'
    | '/qa/reports/teams'
    | '/ts/admin/activation'
    | '/ts/admin/audit-log'
    | '/ts/admin/batches'
    | '/ts/admin/call-results'
    | '/ts/admin/campaigns'
    | '/ts/admin/forms'
    | '/ts/admin/targets'
    | '/ts/admin/users'
    | '/ts/admin/validation'
    | '/ts/admin/warnings'
    | '/ts/reports/agents'
    | '/ts/reports/calls'
    | '/ts/reports/leads'
    | '/qa/reports/evaluations/$id'
    | '/qa/reports/sales-reps/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/qa/call-history'
    | '/_authenticated/qa/call-later'
    | '/_authenticated/qa/work'
    | '/_authenticated/settings/change-password'
    | '/_authenticated/ts/call-history'
    | '/_authenticated/ts/call-later'
    | '/_authenticated/ts/my-report'
    | '/_authenticated/ts/my-warnings'
    | '/_authenticated/ts/work'
    | '/_authenticated/manager/'
    | '/_authenticated/manager/qa/agents'
    | '/_authenticated/manager/qa/batches'
    | '/_authenticated/manager/qa/calls'
    | '/_authenticated/manager/qa/customers'
    | '/_authenticated/manager/qa/evaluations'
    | '/_authenticated/manager/qa/sales-reps'
    | '/_authenticated/manager/qa/teams'
    | '/_authenticated/manager/ts/agents'
    | '/_authenticated/manager/ts/batches'
    | '/_authenticated/manager/ts/calls'
    | '/_authenticated/manager/ts/campaigns'
    | '/_authenticated/manager/ts/leads'
    | '/_authenticated/qa/admin/import'
    | '/_authenticated/qa/admin/sales-reps'
    | '/_authenticated/qa/admin/users'
    | '/_authenticated/qa/reports/agents'
    | '/_authenticated/qa/reports/batches'
    | '/_authenticated/qa/reports/calls'
    | '/_authenticated/qa/reports/customers'
    | '/_authenticated/qa/reports/evaluations'
    | '/_authenticated/qa/reports/sales-reps'
    | '/_authenticated/qa/reports/teams'
    | '/_authenticated/ts/admin/activation'
    | '/_authenticated/ts/admin/audit-log'
    | '/_authenticated/ts/admin/batches'
    | '/_authenticated/ts/admin/call-results'
    | '/_authenticated/ts/admin/campaigns'
    | '/_authenticated/ts/admin/forms'
    | '/_authenticated/ts/admin/targets'
    | '/_authenticated/ts/admin/users'
    | '/_authenticated/ts/admin/validation'
    | '/_authenticated/ts/admin/warnings'
    | '/_authenticated/ts/reports/agents'
    | '/_authenticated/ts/reports/calls'
    | '/_authenticated/ts/reports/leads'
    | '/_authenticated/qa/reports/evaluations/$id'
    | '/_authenticated/qa/reports/sales-reps/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/work': {
      id: '/_authenticated/ts/work'
      path: '/ts/work'
      fullPath: '/ts/work'
      preLoaderRoute: typeof AuthenticatedTsWorkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/my-warnings': {
      id: '/_authenticated/ts/my-warnings'
      path: '/ts/my-warnings'
      fullPath: '/ts/my-warnings'
      preLoaderRoute: typeof AuthenticatedTsMyWarningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/my-report': {
      id: '/_authenticated/ts/my-report'
      path: '/ts/my-report'
      fullPath: '/ts/my-report'
      preLoaderRoute: typeof AuthenticatedTsMyReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/call-later': {
      id: '/_authenticated/ts/call-later'
      path: '/ts/call-later'
      fullPath: '/ts/call-later'
      preLoaderRoute: typeof AuthenticatedTsCallLaterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/call-history': {
      id: '/_authenticated/ts/call-history'
      path: '/ts/call-history'
      fullPath: '/ts/call-history'
      preLoaderRoute: typeof AuthenticatedTsCallHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/change-password': {
      id: '/_authenticated/settings/change-password'
      path: '/settings/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof AuthenticatedSettingsChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/work': {
      id: '/_authenticated/qa/work'
      path: '/qa/work'
      fullPath: '/qa/work'
      preLoaderRoute: typeof AuthenticatedQaWorkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/call-later': {
      id: '/_authenticated/qa/call-later'
      path: '/qa/call-later'
      fullPath: '/qa/call-later'
      preLoaderRoute: typeof AuthenticatedQaCallLaterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/call-history': {
      id: '/_authenticated/qa/call-history'
      path: '/qa/call-history'
      fullPath: '/qa/call-history'
      preLoaderRoute: typeof AuthenticatedQaCallHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/reports/leads': {
      id: '/_authenticated/ts/reports/leads'
      path: '/ts/reports/leads'
      fullPath: '/ts/reports/leads'
      preLoaderRoute: typeof AuthenticatedTsReportsLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/reports/calls': {
      id: '/_authenticated/ts/reports/calls'
      path: '/ts/reports/calls'
      fullPath: '/ts/reports/calls'
      preLoaderRoute: typeof AuthenticatedTsReportsCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/reports/agents': {
      id: '/_authenticated/ts/reports/agents'
      path: '/ts/reports/agents'
      fullPath: '/ts/reports/agents'
      preLoaderRoute: typeof AuthenticatedTsReportsAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/admin/warnings': {
      id: '/_authenticated/ts/admin/warnings'
      path: '/ts/admin/warnings'
      fullPath: '/ts/admin/warnings'
      preLoaderRoute: typeof AuthenticatedTsAdminWarningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/admin/validation': {
      id: '/_authenticated/ts/admin/validation'
      path: '/ts/admin/validation'
      fullPath: '/ts/admin/validation'
      preLoaderRoute: typeof AuthenticatedTsAdminValidationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/admin/users': {
      id: '/_authenticated/ts/admin/users'
      path: '/ts/admin/users'
      fullPath: '/ts/admin/users'
      preLoaderRoute: typeof AuthenticatedTsAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/admin/targets': {
      id: '/_authenticated/ts/admin/targets'
      path: '/ts/admin/targets'
      fullPath: '/ts/admin/targets'
      preLoaderRoute: typeof AuthenticatedTsAdminTargetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/admin/forms': {
      id: '/_authenticated/ts/admin/forms'
      path: '/ts/admin/forms'
      fullPath: '/ts/admin/forms'
      preLoaderRoute: typeof AuthenticatedTsAdminFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/admin/campaigns': {
      id: '/_authenticated/ts/admin/campaigns'
      path: '/ts/admin/campaigns'
      fullPath: '/ts/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedTsAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/admin/call-results': {
      id: '/_authenticated/ts/admin/call-results'
      path: '/ts/admin/call-results'
      fullPath: '/ts/admin/call-results'
      preLoaderRoute: typeof AuthenticatedTsAdminCallResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/admin/batches': {
      id: '/_authenticated/ts/admin/batches'
      path: '/ts/admin/batches'
      fullPath: '/ts/admin/batches'
      preLoaderRoute: typeof AuthenticatedTsAdminBatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/admin/audit-log': {
      id: '/_authenticated/ts/admin/audit-log'
      path: '/ts/admin/audit-log'
      fullPath: '/ts/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedTsAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ts/admin/activation': {
      id: '/_authenticated/ts/admin/activation'
      path: '/ts/admin/activation'
      fullPath: '/ts/admin/activation'
      preLoaderRoute: typeof AuthenticatedTsAdminActivationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/reports/teams': {
      id: '/_authenticated/qa/reports/teams'
      path: '/qa/reports/teams'
      fullPath: '/qa/reports/teams'
      preLoaderRoute: typeof AuthenticatedQaReportsTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/reports/sales-reps': {
      id: '/_authenticated/qa/reports/sales-reps'
      path: '/qa/reports/sales-reps'
      fullPath: '/qa/reports/sales-reps'
      preLoaderRoute: typeof AuthenticatedQaReportsSalesRepsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/reports/evaluations': {
      id: '/_authenticated/qa/reports/evaluations'
      path: '/qa/reports/evaluations'
      fullPath: '/qa/reports/evaluations'
      preLoaderRoute: typeof AuthenticatedQaReportsEvaluationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/reports/customers': {
      id: '/_authenticated/qa/reports/customers'
      path: '/qa/reports/customers'
      fullPath: '/qa/reports/customers'
      preLoaderRoute: typeof AuthenticatedQaReportsCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/reports/calls': {
      id: '/_authenticated/qa/reports/calls'
      path: '/qa/reports/calls'
      fullPath: '/qa/reports/calls'
      preLoaderRoute: typeof AuthenticatedQaReportsCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/reports/batches': {
      id: '/_authenticated/qa/reports/batches'
      path: '/qa/reports/batches'
      fullPath: '/qa/reports/batches'
      preLoaderRoute: typeof AuthenticatedQaReportsBatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/reports/agents': {
      id: '/_authenticated/qa/reports/agents'
      path: '/qa/reports/agents'
      fullPath: '/qa/reports/agents'
      preLoaderRoute: typeof AuthenticatedQaReportsAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/admin/users': {
      id: '/_authenticated/qa/admin/users'
      path: '/qa/admin/users'
      fullPath: '/qa/admin/users'
      preLoaderRoute: typeof AuthenticatedQaAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/admin/sales-reps': {
      id: '/_authenticated/qa/admin/sales-reps'
      path: '/qa/admin/sales-reps'
      fullPath: '/qa/admin/sales-reps'
      preLoaderRoute: typeof AuthenticatedQaAdminSalesRepsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/admin/import': {
      id: '/_authenticated/qa/admin/import'
      path: '/qa/admin/import'
      fullPath: '/qa/admin/import'
      preLoaderRoute: typeof AuthenticatedQaAdminImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/ts/leads': {
      id: '/_authenticated/manager/ts/leads'
      path: '/manager/ts/leads'
      fullPath: '/manager/ts/leads'
      preLoaderRoute: typeof AuthenticatedManagerTsLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/ts/campaigns': {
      id: '/_authenticated/manager/ts/campaigns'
      path: '/manager/ts/campaigns'
      fullPath: '/manager/ts/campaigns'
      preLoaderRoute: typeof AuthenticatedManagerTsCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/ts/calls': {
      id: '/_authenticated/manager/ts/calls'
      path: '/manager/ts/calls'
      fullPath: '/manager/ts/calls'
      preLoaderRoute: typeof AuthenticatedManagerTsCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/ts/batches': {
      id: '/_authenticated/manager/ts/batches'
      path: '/manager/ts/batches'
      fullPath: '/manager/ts/batches'
      preLoaderRoute: typeof AuthenticatedManagerTsBatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/ts/agents': {
      id: '/_authenticated/manager/ts/agents'
      path: '/manager/ts/agents'
      fullPath: '/manager/ts/agents'
      preLoaderRoute: typeof AuthenticatedManagerTsAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/qa/teams': {
      id: '/_authenticated/manager/qa/teams'
      path: '/manager/qa/teams'
      fullPath: '/manager/qa/teams'
      preLoaderRoute: typeof AuthenticatedManagerQaTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/qa/sales-reps': {
      id: '/_authenticated/manager/qa/sales-reps'
      path: '/manager/qa/sales-reps'
      fullPath: '/manager/qa/sales-reps'
      preLoaderRoute: typeof AuthenticatedManagerQaSalesRepsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/qa/evaluations': {
      id: '/_authenticated/manager/qa/evaluations'
      path: '/manager/qa/evaluations'
      fullPath: '/manager/qa/evaluations'
      preLoaderRoute: typeof AuthenticatedManagerQaEvaluationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/qa/customers': {
      id: '/_authenticated/manager/qa/customers'
      path: '/manager/qa/customers'
      fullPath: '/manager/qa/customers'
      preLoaderRoute: typeof AuthenticatedManagerQaCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/qa/calls': {
      id: '/_authenticated/manager/qa/calls'
      path: '/manager/qa/calls'
      fullPath: '/manager/qa/calls'
      preLoaderRoute: typeof AuthenticatedManagerQaCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/qa/batches': {
      id: '/_authenticated/manager/qa/batches'
      path: '/manager/qa/batches'
      fullPath: '/manager/qa/batches'
      preLoaderRoute: typeof AuthenticatedManagerQaBatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/qa/agents': {
      id: '/_authenticated/manager/qa/agents'
      path: '/manager/qa/agents'
      fullPath: '/manager/qa/agents'
      preLoaderRoute: typeof AuthenticatedManagerQaAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa/reports/sales-reps/$id': {
      id: '/_authenticated/qa/reports/sales-reps/$id'
      path: '/$id'
      fullPath: '/qa/reports/sales-reps/$id'
      preLoaderRoute: typeof AuthenticatedQaReportsSalesRepsIdRouteImport
      parentRoute: typeof AuthenticatedQaReportsSalesRepsRoute
    }
    '/_authenticated/qa/reports/evaluations/$id': {
      id: '/_authenticated/qa/reports/evaluations/$id'
      path: '/$id'
      fullPath: '/qa/reports/evaluations/$id'
      preLoaderRoute: typeof AuthenticatedQaReportsEvaluationsIdRouteImport
      parentRoute: typeof AuthenticatedQaReportsEvaluationsRoute
    }
  }
}

interface AuthenticatedQaReportsEvaluationsRouteChildren {
  AuthenticatedQaReportsEvaluationsIdRoute: typeof AuthenticatedQaReportsEvaluationsIdRoute
}

const AuthenticatedQaReportsEvaluationsRouteChildren: AuthenticatedQaReportsEvaluationsRouteChildren =
  {
    AuthenticatedQaReportsEvaluationsIdRoute:
      AuthenticatedQaReportsEvaluationsIdRoute,
  }

const AuthenticatedQaReportsEvaluationsRouteWithChildren =
  AuthenticatedQaReportsEvaluationsRoute._addFileChildren(
    AuthenticatedQaReportsEvaluationsRouteChildren,
  )

interface AuthenticatedQaReportsSalesRepsRouteChildren {
  AuthenticatedQaReportsSalesRepsIdRoute: typeof AuthenticatedQaReportsSalesRepsIdRoute
}

const AuthenticatedQaReportsSalesRepsRouteChildren: AuthenticatedQaReportsSalesRepsRouteChildren =
  {
    AuthenticatedQaReportsSalesRepsIdRoute:
      AuthenticatedQaReportsSalesRepsIdRoute,
  }

const AuthenticatedQaReportsSalesRepsRouteWithChildren =
  AuthenticatedQaReportsSalesRepsRoute._addFileChildren(
    AuthenticatedQaReportsSalesRepsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedQaCallHistoryRoute: typeof AuthenticatedQaCallHistoryRoute
  AuthenticatedQaCallLaterRoute: typeof AuthenticatedQaCallLaterRoute
  AuthenticatedQaWorkRoute: typeof AuthenticatedQaWorkRoute
  AuthenticatedSettingsChangePasswordRoute: typeof AuthenticatedSettingsChangePasswordRoute
  AuthenticatedTsCallHistoryRoute: typeof AuthenticatedTsCallHistoryRoute
  AuthenticatedTsCallLaterRoute: typeof AuthenticatedTsCallLaterRoute
  AuthenticatedTsMyReportRoute: typeof AuthenticatedTsMyReportRoute
  AuthenticatedTsMyWarningsRoute: typeof AuthenticatedTsMyWarningsRoute
  AuthenticatedTsWorkRoute: typeof AuthenticatedTsWorkRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
  AuthenticatedManagerQaAgentsRoute: typeof AuthenticatedManagerQaAgentsRoute
  AuthenticatedManagerQaBatchesRoute: typeof AuthenticatedManagerQaBatchesRoute
  AuthenticatedManagerQaCallsRoute: typeof AuthenticatedManagerQaCallsRoute
  AuthenticatedManagerQaCustomersRoute: typeof AuthenticatedManagerQaCustomersRoute
  AuthenticatedManagerQaEvaluationsRoute: typeof AuthenticatedManagerQaEvaluationsRoute
  AuthenticatedManagerQaSalesRepsRoute: typeof AuthenticatedManagerQaSalesRepsRoute
  AuthenticatedManagerQaTeamsRoute: typeof AuthenticatedManagerQaTeamsRoute
  AuthenticatedManagerTsAgentsRoute: typeof AuthenticatedManagerTsAgentsRoute
  AuthenticatedManagerTsBatchesRoute: typeof AuthenticatedManagerTsBatchesRoute
  AuthenticatedManagerTsCallsRoute: typeof AuthenticatedManagerTsCallsRoute
  AuthenticatedManagerTsCampaignsRoute: typeof AuthenticatedManagerTsCampaignsRoute
  AuthenticatedManagerTsLeadsRoute: typeof AuthenticatedManagerTsLeadsRoute
  AuthenticatedQaAdminImportRoute: typeof AuthenticatedQaAdminImportRoute
  AuthenticatedQaAdminSalesRepsRoute: typeof AuthenticatedQaAdminSalesRepsRoute
  AuthenticatedQaAdminUsersRoute: typeof AuthenticatedQaAdminUsersRoute
  AuthenticatedQaReportsAgentsRoute: typeof AuthenticatedQaReportsAgentsRoute
  AuthenticatedQaReportsBatchesRoute: typeof AuthenticatedQaReportsBatchesRoute
  AuthenticatedQaReportsCallsRoute: typeof AuthenticatedQaReportsCallsRoute
  AuthenticatedQaReportsCustomersRoute: typeof AuthenticatedQaReportsCustomersRoute
  AuthenticatedQaReportsEvaluationsRoute: typeof AuthenticatedQaReportsEvaluationsRouteWithChildren
  AuthenticatedQaReportsSalesRepsRoute: typeof AuthenticatedQaReportsSalesRepsRouteWithChildren
  AuthenticatedQaReportsTeamsRoute: typeof AuthenticatedQaReportsTeamsRoute
  AuthenticatedTsAdminActivationRoute: typeof AuthenticatedTsAdminActivationRoute
  AuthenticatedTsAdminAuditLogRoute: typeof AuthenticatedTsAdminAuditLogRoute
  AuthenticatedTsAdminBatchesRoute: typeof AuthenticatedTsAdminBatchesRoute
  AuthenticatedTsAdminCallResultsRoute: typeof AuthenticatedTsAdminCallResultsRoute
  AuthenticatedTsAdminCampaignsRoute: typeof AuthenticatedTsAdminCampaignsRoute
  AuthenticatedTsAdminFormsRoute: typeof AuthenticatedTsAdminFormsRoute
  AuthenticatedTsAdminTargetsRoute: typeof AuthenticatedTsAdminTargetsRoute
  AuthenticatedTsAdminUsersRoute: typeof AuthenticatedTsAdminUsersRoute
  AuthenticatedTsAdminValidationRoute: typeof AuthenticatedTsAdminValidationRoute
  AuthenticatedTsAdminWarningsRoute: typeof AuthenticatedTsAdminWarningsRoute
  AuthenticatedTsReportsAgentsRoute: typeof AuthenticatedTsReportsAgentsRoute
  AuthenticatedTsReportsCallsRoute: typeof AuthenticatedTsReportsCallsRoute
  AuthenticatedTsReportsLeadsRoute: typeof AuthenticatedTsReportsLeadsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedQaCallHistoryRoute: AuthenticatedQaCallHistoryRoute,
  AuthenticatedQaCallLaterRoute: AuthenticatedQaCallLaterRoute,
  AuthenticatedQaWorkRoute: AuthenticatedQaWorkRoute,
  AuthenticatedSettingsChangePasswordRoute:
    AuthenticatedSettingsChangePasswordRoute,
  AuthenticatedTsCallHistoryRoute: AuthenticatedTsCallHistoryRoute,
  AuthenticatedTsCallLaterRoute: AuthenticatedTsCallLaterRoute,
  AuthenticatedTsMyReportRoute: AuthenticatedTsMyReportRoute,
  AuthenticatedTsMyWarningsRoute: AuthenticatedTsMyWarningsRoute,
  AuthenticatedTsWorkRoute: AuthenticatedTsWorkRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
  AuthenticatedManagerQaAgentsRoute: AuthenticatedManagerQaAgentsRoute,
  AuthenticatedManagerQaBatchesRoute: AuthenticatedManagerQaBatchesRoute,
  AuthenticatedManagerQaCallsRoute: AuthenticatedManagerQaCallsRoute,
  AuthenticatedManagerQaCustomersRoute: AuthenticatedManagerQaCustomersRoute,
  AuthenticatedManagerQaEvaluationsRoute:
    AuthenticatedManagerQaEvaluationsRoute,
  AuthenticatedManagerQaSalesRepsRoute: AuthenticatedManagerQaSalesRepsRoute,
  AuthenticatedManagerQaTeamsRoute: AuthenticatedManagerQaTeamsRoute,
  AuthenticatedManagerTsAgentsRoute: AuthenticatedManagerTsAgentsRoute,
  AuthenticatedManagerTsBatchesRoute: AuthenticatedManagerTsBatchesRoute,
  AuthenticatedManagerTsCallsRoute: AuthenticatedManagerTsCallsRoute,
  AuthenticatedManagerTsCampaignsRoute: AuthenticatedManagerTsCampaignsRoute,
  AuthenticatedManagerTsLeadsRoute: AuthenticatedManagerTsLeadsRoute,
  AuthenticatedQaAdminImportRoute: AuthenticatedQaAdminImportRoute,
  AuthenticatedQaAdminSalesRepsRoute: AuthenticatedQaAdminSalesRepsRoute,
  AuthenticatedQaAdminUsersRoute: AuthenticatedQaAdminUsersRoute,
  AuthenticatedQaReportsAgentsRoute: AuthenticatedQaReportsAgentsRoute,
  AuthenticatedQaReportsBatchesRoute: AuthenticatedQaReportsBatchesRoute,
  AuthenticatedQaReportsCallsRoute: AuthenticatedQaReportsCallsRoute,
  AuthenticatedQaReportsCustomersRoute: AuthenticatedQaReportsCustomersRoute,
  AuthenticatedQaReportsEvaluationsRoute:
    AuthenticatedQaReportsEvaluationsRouteWithChildren,
  AuthenticatedQaReportsSalesRepsRoute:
    AuthenticatedQaReportsSalesRepsRouteWithChildren,
  AuthenticatedQaReportsTeamsRoute: AuthenticatedQaReportsTeamsRoute,
  AuthenticatedTsAdminActivationRoute: AuthenticatedTsAdminActivationRoute,
  AuthenticatedTsAdminAuditLogRoute: AuthenticatedTsAdminAuditLogRoute,
  AuthenticatedTsAdminBatchesRoute: AuthenticatedTsAdminBatchesRoute,
  AuthenticatedTsAdminCallResultsRoute: AuthenticatedTsAdminCallResultsRoute,
  AuthenticatedTsAdminCampaignsRoute: AuthenticatedTsAdminCampaignsRoute,
  AuthenticatedTsAdminFormsRoute: AuthenticatedTsAdminFormsRoute,
  AuthenticatedTsAdminTargetsRoute: AuthenticatedTsAdminTargetsRoute,
  AuthenticatedTsAdminUsersRoute: AuthenticatedTsAdminUsersRoute,
  AuthenticatedTsAdminValidationRoute: AuthenticatedTsAdminValidationRoute,
  AuthenticatedTsAdminWarningsRoute: AuthenticatedTsAdminWarningsRoute,
  AuthenticatedTsReportsAgentsRoute: AuthenticatedTsReportsAgentsRoute,
  AuthenticatedTsReportsCallsRoute: AuthenticatedTsReportsCallsRoute,
  AuthenticatedTsReportsLeadsRoute: AuthenticatedTsReportsLeadsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
